preset: laravel

enabled:
  - concat_with_spaces

disabled:
  - unalign_equals
  - not_operator_with_successor_space
  - concat_without_spaces
  - method_visibility_required
  - simplified_null_return
